package model;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Sep 11 15:28:20 EDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XxChildSkusImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Mastersku,
        Color,
        Code,
        Size1,
        Size2,
        Size3,
        Size4,
        Size5,
        Size6,
        Size7,
        Size8,
        Size9,
        Size10,
        Size11,
        Size12,
        Size13,
        Size14,
        Size15,
        Size16,
        Size17,
        Size18,
        Size1Descr,
        MasterskuDescr,
        Size2Descr,
        Size3Descr,
        Size4Descr,
        Size5Descr,
        Size6Descr,
        Size7Descr,
        Size8Descr,
        Size9Descr,
        Size10Descr,
        Size11Descr,
        Size12Descr,
        Size13Descr,
        Size14Descr,
        Size15Descr,
        Size16Descr,
        Size17Descr,
        Size18Descr;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int MASTERSKU = AttributesEnum.Mastersku.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int CODE = AttributesEnum.Code.index();
    public static final int SIZE1 = AttributesEnum.Size1.index();
    public static final int SIZE2 = AttributesEnum.Size2.index();
    public static final int SIZE3 = AttributesEnum.Size3.index();
    public static final int SIZE4 = AttributesEnum.Size4.index();
    public static final int SIZE5 = AttributesEnum.Size5.index();
    public static final int SIZE6 = AttributesEnum.Size6.index();
    public static final int SIZE7 = AttributesEnum.Size7.index();
    public static final int SIZE8 = AttributesEnum.Size8.index();
    public static final int SIZE9 = AttributesEnum.Size9.index();
    public static final int SIZE10 = AttributesEnum.Size10.index();
    public static final int SIZE11 = AttributesEnum.Size11.index();
    public static final int SIZE12 = AttributesEnum.Size12.index();
    public static final int SIZE13 = AttributesEnum.Size13.index();
    public static final int SIZE14 = AttributesEnum.Size14.index();
    public static final int SIZE15 = AttributesEnum.Size15.index();
    public static final int SIZE16 = AttributesEnum.Size16.index();
    public static final int SIZE17 = AttributesEnum.Size17.index();
    public static final int SIZE18 = AttributesEnum.Size18.index();
    public static final int SIZE1DESCR = AttributesEnum.Size1Descr.index();
    public static final int MASTERSKUDESCR = AttributesEnum.MasterskuDescr.index();
    public static final int SIZE2DESCR = AttributesEnum.Size2Descr.index();
    public static final int SIZE3DESCR = AttributesEnum.Size3Descr.index();
    public static final int SIZE4DESCR = AttributesEnum.Size4Descr.index();
    public static final int SIZE5DESCR = AttributesEnum.Size5Descr.index();
    public static final int SIZE6DESCR = AttributesEnum.Size6Descr.index();
    public static final int SIZE7DESCR = AttributesEnum.Size7Descr.index();
    public static final int SIZE8DESCR = AttributesEnum.Size8Descr.index();
    public static final int SIZE9DESCR = AttributesEnum.Size9Descr.index();
    public static final int SIZE10DESCR = AttributesEnum.Size10Descr.index();
    public static final int SIZE11DESCR = AttributesEnum.Size11Descr.index();
    public static final int SIZE12DESCR = AttributesEnum.Size12Descr.index();
    public static final int SIZE13DESCR = AttributesEnum.Size13Descr.index();
    public static final int SIZE14DESCR = AttributesEnum.Size14Descr.index();
    public static final int SIZE15DESCR = AttributesEnum.Size15Descr.index();
    public static final int SIZE16DESCR = AttributesEnum.Size16Descr.index();
    public static final int SIZE17DESCR = AttributesEnum.Size17Descr.index();
    public static final int SIZE18DESCR = AttributesEnum.Size18Descr.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XxChildSkusImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.XxChildSkus");
    }


    /**
     * Gets the attribute value for Mastersku, using the alias name Mastersku.
     * @return the value of Mastersku
     */
    public String getMastersku() {
        return (String) getAttributeInternal(MASTERSKU);
    }

    /**
     * Sets <code>value</code> as the attribute value for Mastersku.
     * @param value value to set the Mastersku
     */
    public void setMastersku(String value) {
        setAttributeInternal(MASTERSKU, value);
    }

    /**
     * Gets the attribute value for Color, using the alias name Color.
     * @return the value of Color
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Color.
     * @param value value to set the Color
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for Code, using the alias name Code.
     * @return the value of Code
     */
    public String getCode() {
        return (String) getAttributeInternal(CODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Code.
     * @param value value to set the Code
     */
    public void setCode(String value) {
        setAttributeInternal(CODE, value);
    }

    /**
     * Gets the attribute value for Size1, using the alias name Size1.
     * @return the value of Size1
     */
    public String getSize1() {
        return (String) getAttributeInternal(SIZE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size1.
     * @param value value to set the Size1
     */
    public void setSize1(String value) {
        setAttributeInternal(SIZE1, value);
    }

    /**
     * Gets the attribute value for Size2, using the alias name Size2.
     * @return the value of Size2
     */
    public String getSize2() {
        return (String) getAttributeInternal(SIZE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size2.
     * @param value value to set the Size2
     */
    public void setSize2(String value) {
        setAttributeInternal(SIZE2, value);
    }

    /**
     * Gets the attribute value for Size3, using the alias name Size3.
     * @return the value of Size3
     */
    public String getSize3() {
        return (String) getAttributeInternal(SIZE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size3.
     * @param value value to set the Size3
     */
    public void setSize3(String value) {
        setAttributeInternal(SIZE3, value);
    }

    /**
     * Gets the attribute value for Size4, using the alias name Size4.
     * @return the value of Size4
     */
    public String getSize4() {
        return (String) getAttributeInternal(SIZE4);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size4.
     * @param value value to set the Size4
     */
    public void setSize4(String value) {
        setAttributeInternal(SIZE4, value);
    }

    /**
     * Gets the attribute value for Size5, using the alias name Size5.
     * @return the value of Size5
     */
    public String getSize5() {
        return (String) getAttributeInternal(SIZE5);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size5.
     * @param value value to set the Size5
     */
    public void setSize5(String value) {
        setAttributeInternal(SIZE5, value);
    }

    /**
     * Gets the attribute value for Size6, using the alias name Size6.
     * @return the value of Size6
     */
    public String getSize6() {
        return (String) getAttributeInternal(SIZE6);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size6.
     * @param value value to set the Size6
     */
    public void setSize6(String value) {
        setAttributeInternal(SIZE6, value);
    }

    /**
     * Gets the attribute value for Size7, using the alias name Size7.
     * @return the value of Size7
     */
    public String getSize7() {
        return (String) getAttributeInternal(SIZE7);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size7.
     * @param value value to set the Size7
     */
    public void setSize7(String value) {
        setAttributeInternal(SIZE7, value);
    }

    /**
     * Gets the attribute value for Size8, using the alias name Size8.
     * @return the value of Size8
     */
    public String getSize8() {
        return (String) getAttributeInternal(SIZE8);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size8.
     * @param value value to set the Size8
     */
    public void setSize8(String value) {
        setAttributeInternal(SIZE8, value);
    }

    /**
     * Gets the attribute value for Size9, using the alias name Size9.
     * @return the value of Size9
     */
    public String getSize9() {
        return (String) getAttributeInternal(SIZE9);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size9.
     * @param value value to set the Size9
     */
    public void setSize9(String value) {
        setAttributeInternal(SIZE9, value);
    }

    /**
     * Gets the attribute value for Size10, using the alias name Size10.
     * @return the value of Size10
     */
    public String getSize10() {
        return (String) getAttributeInternal(SIZE10);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size10.
     * @param value value to set the Size10
     */
    public void setSize10(String value) {
        setAttributeInternal(SIZE10, value);
    }

    /**
     * Gets the attribute value for Size11, using the alias name Size11.
     * @return the value of Size11
     */
    public String getSize11() {
        return (String) getAttributeInternal(SIZE11);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size11.
     * @param value value to set the Size11
     */
    public void setSize11(String value) {
        setAttributeInternal(SIZE11, value);
    }

    /**
     * Gets the attribute value for Size12, using the alias name Size12.
     * @return the value of Size12
     */
    public String getSize12() {
        return (String) getAttributeInternal(SIZE12);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size12.
     * @param value value to set the Size12
     */
    public void setSize12(String value) {
        setAttributeInternal(SIZE12, value);
    }

    /**
     * Gets the attribute value for Size13, using the alias name Size13.
     * @return the value of Size13
     */
    public String getSize13() {
        return (String) getAttributeInternal(SIZE13);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size13.
     * @param value value to set the Size13
     */
    public void setSize13(String value) {
        setAttributeInternal(SIZE13, value);
    }

    /**
     * Gets the attribute value for Size14, using the alias name Size14.
     * @return the value of Size14
     */
    public String getSize14() {
        return (String) getAttributeInternal(SIZE14);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size14.
     * @param value value to set the Size14
     */
    public void setSize14(String value) {
        setAttributeInternal(SIZE14, value);
    }

    /**
     * Gets the attribute value for Size15, using the alias name Size15.
     * @return the value of Size15
     */
    public String getSize15() {
        return (String) getAttributeInternal(SIZE15);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size15.
     * @param value value to set the Size15
     */
    public void setSize15(String value) {
        setAttributeInternal(SIZE15, value);
    }

    /**
     * Gets the attribute value for Size16, using the alias name Size16.
     * @return the value of Size16
     */
    public String getSize16() {
        return (String) getAttributeInternal(SIZE16);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size16.
     * @param value value to set the Size16
     */
    public void setSize16(String value) {
        setAttributeInternal(SIZE16, value);
    }

    /**
     * Gets the attribute value for Size17, using the alias name Size17.
     * @return the value of Size17
     */
    public String getSize17() {
        return (String) getAttributeInternal(SIZE17);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size17.
     * @param value value to set the Size17
     */
    public void setSize17(String value) {
        setAttributeInternal(SIZE17, value);
    }

    /**
     * Gets the attribute value for Size18, using the alias name Size18.
     * @return the value of Size18
     */
    public String getSize18() {
        return (String) getAttributeInternal(SIZE18);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size18.
     * @param value value to set the Size18
     */
    public void setSize18(String value) {
        setAttributeInternal(SIZE18, value);
    }

    /**
     * Gets the attribute value for Size1Descr, using the alias name Size1Descr.
     * @return the value of Size1Descr
     */
    public String getSize1Descr() {
        return (String) getAttributeInternal(SIZE1DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size1Descr.
     * @param value value to set the Size1Descr
     */
    public void setSize1Descr(String value) {
        setAttributeInternal(SIZE1DESCR, value);
    }

    /**
     * Gets the attribute value for MasterskuDescr, using the alias name MasterskuDescr.
     * @return the value of MasterskuDescr
     */
    public String getMasterskuDescr() {
        return (String) getAttributeInternal(MASTERSKUDESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for MasterskuDescr.
     * @param value value to set the MasterskuDescr
     */
    public void setMasterskuDescr(String value) {
        setAttributeInternal(MASTERSKUDESCR, value);
    }


    /**
     * Gets the attribute value for Size2Descr, using the alias name Size2Descr.
     * @return the value of Size2Descr
     */
    public String getSize2Descr() {
        return (String) getAttributeInternal(SIZE2DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size2Descr.
     * @param value value to set the Size2Descr
     */
    public void setSize2Descr(String value) {
        setAttributeInternal(SIZE2DESCR, value);
    }

    /**
     * Gets the attribute value for Size3Descr, using the alias name Size3Descr.
     * @return the value of Size3Descr
     */
    public String getSize3Descr() {
        return (String) getAttributeInternal(SIZE3DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size3Descr.
     * @param value value to set the Size3Descr
     */
    public void setSize3Descr(String value) {
        setAttributeInternal(SIZE3DESCR, value);
    }

    /**
     * Gets the attribute value for Size4Descr, using the alias name Size4Descr.
     * @return the value of Size4Descr
     */
    public String getSize4Descr() {
        return (String) getAttributeInternal(SIZE4DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size4Descr.
     * @param value value to set the Size4Descr
     */
    public void setSize4Descr(String value) {
        setAttributeInternal(SIZE4DESCR, value);
    }

    /**
     * Gets the attribute value for Size5Descr, using the alias name Size5Descr.
     * @return the value of Size5Descr
     */
    public String getSize5Descr() {
        return (String) getAttributeInternal(SIZE5DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size5Descr.
     * @param value value to set the Size5Descr
     */
    public void setSize5Descr(String value) {
        setAttributeInternal(SIZE5DESCR, value);
    }

    /**
     * Gets the attribute value for Size6Descr, using the alias name Size6Descr.
     * @return the value of Size6Descr
     */
    public String getSize6Descr() {
        return (String) getAttributeInternal(SIZE6DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size6Descr.
     * @param value value to set the Size6Descr
     */
    public void setSize6Descr(String value) {
        setAttributeInternal(SIZE6DESCR, value);
    }

    /**
     * Gets the attribute value for Size7Descr, using the alias name Size7Descr.
     * @return the value of Size7Descr
     */
    public String getSize7Descr() {
        return (String) getAttributeInternal(SIZE7DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size7Descr.
     * @param value value to set the Size7Descr
     */
    public void setSize7Descr(String value) {
        setAttributeInternal(SIZE7DESCR, value);
    }

    /**
     * Gets the attribute value for Size8Descr, using the alias name Size8Descr.
     * @return the value of Size8Descr
     */
    public String getSize8Descr() {
        return (String) getAttributeInternal(SIZE8DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size8Descr.
     * @param value value to set the Size8Descr
     */
    public void setSize8Descr(String value) {
        setAttributeInternal(SIZE8DESCR, value);
    }

    /**
     * Gets the attribute value for Size9Descr, using the alias name Size9Descr.
     * @return the value of Size9Descr
     */
    public String getSize9Descr() {
        return (String) getAttributeInternal(SIZE9DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size9Descr.
     * @param value value to set the Size9Descr
     */
    public void setSize9Descr(String value) {
        setAttributeInternal(SIZE9DESCR, value);
    }

    /**
     * Gets the attribute value for Size10Descr, using the alias name Size10Descr.
     * @return the value of Size10Descr
     */
    public String getSize10Descr() {
        return (String) getAttributeInternal(SIZE10DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size10Descr.
     * @param value value to set the Size10Descr
     */
    public void setSize10Descr(String value) {
        setAttributeInternal(SIZE10DESCR, value);
    }

    /**
     * Gets the attribute value for Size11Descr, using the alias name Size11Descr.
     * @return the value of Size11Descr
     */
    public String getSize11Descr() {
        return (String) getAttributeInternal(SIZE11DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size11Descr.
     * @param value value to set the Size11Descr
     */
    public void setSize11Descr(String value) {
        setAttributeInternal(SIZE11DESCR, value);
    }

    /**
     * Gets the attribute value for Size12Descr, using the alias name Size12Descr.
     * @return the value of Size12Descr
     */
    public String getSize12Descr() {
        return (String) getAttributeInternal(SIZE12DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size12Descr.
     * @param value value to set the Size12Descr
     */
    public void setSize12Descr(String value) {
        setAttributeInternal(SIZE12DESCR, value);
    }

    /**
     * Gets the attribute value for Size13Descr, using the alias name Size13Descr.
     * @return the value of Size13Descr
     */
    public String getSize13Descr() {
        return (String) getAttributeInternal(SIZE13DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size13Descr.
     * @param value value to set the Size13Descr
     */
    public void setSize13Descr(String value) {
        setAttributeInternal(SIZE13DESCR, value);
    }

    /**
     * Gets the attribute value for Size14Descr, using the alias name Size14Descr.
     * @return the value of Size14Descr
     */
    public String getSize14Descr() {
        return (String) getAttributeInternal(SIZE14DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size14Descr.
     * @param value value to set the Size14Descr
     */
    public void setSize14Descr(String value) {
        setAttributeInternal(SIZE14DESCR, value);
    }

    /**
     * Gets the attribute value for Size15Descr, using the alias name Size15Descr.
     * @return the value of Size15Descr
     */
    public String getSize15Descr() {
        return (String) getAttributeInternal(SIZE15DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size15Descr.
     * @param value value to set the Size15Descr
     */
    public void setSize15Descr(String value) {
        setAttributeInternal(SIZE15DESCR, value);
    }

    /**
     * Gets the attribute value for Size16Descr, using the alias name Size16Descr.
     * @return the value of Size16Descr
     */
    public String getSize16Descr() {
        return (String) getAttributeInternal(SIZE16DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size16Descr.
     * @param value value to set the Size16Descr
     */
    public void setSize16Descr(String value) {
        setAttributeInternal(SIZE16DESCR, value);
    }

    /**
     * Gets the attribute value for Size17Descr, using the alias name Size17Descr.
     * @return the value of Size17Descr
     */
    public String getSize17Descr() {
        return (String) getAttributeInternal(SIZE17DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size17Descr.
     * @param value value to set the Size17Descr
     */
    public void setSize17Descr(String value) {
        setAttributeInternal(SIZE17DESCR, value);
    }

    /**
     * Gets the attribute value for Size18Descr, using the alias name Size18Descr.
     * @return the value of Size18Descr
     */
    public String getSize18Descr() {
        return (String) getAttributeInternal(SIZE18DESCR);
    }

    /**
     * Sets <code>value</code> as the attribute value for Size18Descr.
     * @param value value to set the Size18Descr
     */
    public void setSize18Descr(String value) {
        setAttributeInternal(SIZE18DESCR, value);
    }

    /**
     * @param size1 key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String size1) {
        return new Key(new Object[] { size1 });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

