package model;

import model.common.AppModule;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 12 12:00:50 EDT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for XxChildSkusView1.
     * @return XxChildSkusView1
     */
    public ViewObjectImpl getXxChildSkusView1() {
        return (ViewObjectImpl) findViewObject("XxChildSkusView1");
    }

    /**
     * Container's getter for MasterskuLOV1.
     * @return MasterskuLOV1
     */
    public ViewObjectImpl getMasterskuLOV1() {
        return (ViewObjectImpl) findViewObject("MasterskuLOV1");
    }

    /**
     * Container's getter for ForecastVO1.
     * @return ForecastVO1
     */
    public ViewObjectImpl getForecastVO1() {
        return (ViewObjectImpl) findViewObject("ForecastVO1");
    }

    /**
     * Container's getter for xxGetChildSKUVO1.
     * @return xxGetChildSKUVO1
     */
    public xxGetChildSKUVOImpl getxxGetChildSKUVO1() {
        return (xxGetChildSKUVOImpl) findViewObject("xxGetChildSKUVO1");
    }
    public void getChildSKUDetails(String masterSKU){
   ViewObjectImpl vo= getxxGetChildSKUVO1();
   System.out.println("Master SKU Value is"+masterSKU);
   vo.setWhereClauseParam(0, masterSKU);
   vo.executeQuery();   
 }
}

