package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 12 12:11:41 EDT 2016
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void getChildSKUDetails(String masterSKU);
}

